### ISSUE TITLE
GRBL Driver PSoC5.cydsn

### ISSUE THREAD

**Issue by gelius59** [terjeio/PSoC5GrblDriver#1]
Hello
excuse me.
I do everything according to your instructions.
Creator gives an error " Build error: grbllib.h: No such file or directory"
What is your advice?
I'm new to PSoC

**Comment by terjeio** [comment]
Did you follow the "How to set up build environment" instructions I have added to the project? It could be that you have not added the dependency to the grbl library project.

**Comment by gelius59** [comment]
Hello.
The instruction was carried out completely.
dependency
Also added.
Anyway an error😒


>Вторник, 26 сентября 2017, 14:01 +03:00 от Terje Io <notifications@github.com>:
>
>Did you follow the "How to set up build environment" instructions I have added to the project? It could be that you have not added the dependency to the grbl library project.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


Best regards.
Yrij.
С Уважением.
Юрий.
--------------------------------
Yrij Shincarenko 
35000, Kostopol, Ukraine
email: gelius59@mail.ru
