### ISSUE TITLE
dependency

### ISSUE THREAD

**Issue by gelius59** [terjeio/PSoC5GrblDriver#2]
Hello.
The instruction was carried out completely.
dependency
Also added.
Anyway an error😒

**Comment by terjeio** [comment]
When you expand Header Files and Source Files for the GRBL Library project is **all** the .c and .h files from that project listed?

**Comment by gelius59** [comment]
Yes.


>Вторник, 26 сентября 2017, 14:37 +03:00 от Terje Io <notifications@github.com>:
>
>When you expand Header Files and Source Files for the GRBL Library project is  all the .c and .h files from that project listed?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


Best regards.
Yrij.
С Уважением.
Юрий.
--------------------------------
Yrij Shincarenko 
35000, Kostopol, Ukraine
email: gelius59@mail.ru
