### ISSUE TITLE
PSoC5GrblDriver + grblLib

### ISSUE THREAD

**Issue by gelius59** [terjeio/PSoC5GrblDriver#3]
Excuse me.
Could you send me your project.
PSoC5GrblDriver + grblLib
Perhaps this is how I soon understand that I have a problem

**Comment by terjeio** [comment]
I have to verify my instructions again first to see if there is any errors there. Will do that a bit later, dinner time here. Also, there is no need to open an new issue, you can add replies to this one as needed.

**Comment by gelius59** [comment]
OK
Thank you.
I'll wait


>Вторник, 26 сентября 2017, 14:46 +03:00 от Terje Io <notifications@github.com>:
>
>I have to verify my instructions again first to see if there is any errors there. Will do that a bit later, dinner time here. Also, there is no need to open an new issue, you can add replies to this one as needed.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


Best regards.
Yrij.
С Уважением.
Юрий.
--------------------------------
Yrij Shincarenko 
35000, Kostopol, Ukraine
email: gelius59@mail.ru

**Comment by terjeio** [comment]
[grbl.cywrk.Archive01.zip](https://github.com/terjeio/PSoC5GrblDriver/files/1333263/grbl.cywrk.Archive01.zip)

Here is a zip-file that I made from a new workspace that I created, this from newly downloaded files and by following the instructions. I do not know why it fails for you since it compiles without errors for me.

**Comment by gelius59** [comment]
OK
Thank you
I will watch


>Вторник, 26 сентября 2017, 16:22 +03:00 от Terje Io <notifications@github.com>:
>
>grbl.cywrk.Archive01.zip
>Here is a zip-file that I made from a new workspace that I created, this from newly downloaded files and by following the instructions. I do not know why it fails for you since it compiles without errors for me.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


Best regards.
Yrij.
С Уважением.
Юрий.
--------------------------------
Yrij Shincarenko 
35000, Kostopol, Ukraine
email: gelius59@mail.ru

**Comment by terjeio** [comment]
Did you download and sucessfully build the project in the workspace-archive I provided in the zip-file above?

**Comment by gelius59** [comment]
Hello.
Sorry for not telling you the result.
Your project has uploaded.
He is just like mine.
Still does not work.
The project does not see the library "grbllib.h" I'm looking for the cause of the problem.


>Среда, 27 сентября 2017, 2:36 +03:00 от Terje Io <notifications@github.com>:
>
>Did you download and sucessfully build the project in the workspace-archive I provided in the zip-file above?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


Best regards.
Yrij.
С Уважением.
Юрий.
--------------------------------
Yrij Shincarenko 
35000, Kostopol, Ukraine
email: gelius59@mail.ru

**Comment by gelius59** [comment]
Oh
Found a solution.
One night without sleep.😄
Did as in the pictures.
https://1drv.ms/f/s!AkCLEVnlznYugocksON3pfCImIpNdA

I think problemma in windows, I have a Russian version.
With the wrong definition of the paths to the files, I have already met several times.


>Среда, 27 сентября 2017, 2:36 +03:00 от Terje Io <notifications@github.com>:
>
>Did you download and sucessfully build the project in the workspace-archive I provided in the zip-file above?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


Best regards.
Yrij.
С Уважением.
Юрий.
--------------------------------
Yrij Shincarenko 
35000, Kostopol, Ukraine
email: gelius59@mail.ru
